### ISSUE TITLE
Duplicated string in code TouchImageView.java

### ISSUE THREAD

**Issue by Ozbern** [hannesa2/TouchImageView#12]
@Override
        public boolean onTouch(View v, MotionEvent event) {
            if (getDrawable() == null) {
                setState(State.NONE);
                return false;
            }
            mScaleDetector.onTouchEvent(event);   
            mScaleDetector.onTouchEvent(event);    //!!!!!!!!!!   Duplicate. As a result - Unexpected scroll behavior
            mGestureDetector.onTouchEvent(event)

**Comment by hannesa2** [comment]
Thank you for the report https://github.com/hannesa2/TouchImageView/pull/13

**Comment by hannesa2** [comment]
https://github.com/hannesa2/TouchImageView/releases/tag/2.1.1 This is a AndroidX version or do you need a supportLib one ?

**Comment by Ozbern** [comment]
> https://github.com/hannesa2/TouchImageView/releases/tag/2.1.1 This is a AndroidX version or do you need a supportLib one ?

Just TouchImageView.java file in my project.
Thank You
