### ISSUE TITLE
Does not support sharedElementTransition

### ISSUE THREAD

**Issue by TrevinAvery** [hannesa2/TouchImageView#14]
I am using a shared element transition to slide a picture from one fragment to another. In the first fragment it is in the top left corner of the screen, and the second it is full screen. When I do, the image just shrinks into the top left corner and disappears. Then, when I touch the screen, it suddenly appears full screen.

This works just fine when both images are normal `ImageView`s, but it fails if either or both are `TouchImageView`.

**Comment by Ruberik** [comment]
@TrevinAvery If you're hoping to debug it yourself, you could take a look at the zoom level after you drag it. Perhaps that's somehow being set to 0, and that's why the image is shrinking and disappearing.
