### ISSUE TITLE
On rotation, zoom is retained but position isn't

### ISSUE THREAD

**Issue by Ruberik** [hannesa2/TouchImageView#4]
To reproduce:

1. Open the sample app in portrait mode.
2. Tap "single touchimageview"
3. Zoom in as much as possible to the bottom-right corner.
4. Rotate to landscape mode.

Expected result: The TouchImageView either:
1. Displays 1.0 zoom, as if the Activity had been opened in landscape mode in the first place, OR
2. Retains its zoom, as well as _something like_ its position.

Actual result:
The TouchImageView retains its zoom, in the top-left corner of the image.

I believe my expected result 2 was intended, because (a) there's a function called translateMatrixAfterRotate, and (b) translateMatrixAfterRotate sure seems to be trying to translate the image to a spot with a similar centre after a rotation change.

**Comment by Ruberik** [comment]
I'm digging into this now, but made a bug to track it just in case you have some feedback (or a burning desire to do it yourself).

**Comment by hannesa2** [comment]
I see it doesn't take care about the position, just on zoom level.
To be honest, I'm happy when you make a PR
